// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;  
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ✅ CONFIGURACIÓN PARA WEB (agregada)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAKINXqhuu59K91J78_wCHk0o5xZC8nn8',
    appId: '1:514722757577:web:7cb22f11b80f3ee1090618',  // Usando el mismo que Android temporalmente
    messagingSenderId: '514722757577',
    projectId: 'doctorappointmentapp-583ab',
    authDomain: 'doctorappointmentapp-583ab.firebaseapp.com',
    storageBucket: 'doctorappointmentapp-583ab.firebasestorage.app',
  );

  // ✅ CONFIGURACIÓN PARA ANDROID (tu configuración original)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAKINXqhuu59K91J78_wCHk0o5xZC8nn8',
    appId: '1:514722757577:android:7cb22f11b80f3ee1090618',
    messagingSenderId: '514722757577',
    projectId: 'doctorappointmentapp-583ab',
    storageBucket: 'doctorappointmentapp-583ab.firebasestorage.app',
  );
}